### ISSUE TITLE
Issue using winston-loggly-bulk with winston 2.3.x

### ISSUE THREAD

**Issue by sloops77** [loggly/winston-loggly-bulk#10] opened 2017-02-02 11:01 UTC
See https://github.com/winstonjs/winston/issues/947

**Comment by Shwetajain148** [comment] 2017-06-06 10:16
@sloops77, I setup **Winston** and **winston-loggly-bulk** on my machine and tried to reproduce this issue at my end but I couldn't see any error as mentioned in above link. I also setup Winston v**2.3.0**and v**2.3.1**(because you mentioned "Issue using winston-loggly-bulk with Winston v**2.3.x**") with different node versions like- **4.5.0**, **6.10.1** and **7.7.2** but didn't face any issue. 

I am attaching my code snippet that I tried with and what standard format loggly suggests to log any string or object when you are using **winston-loggly-bulk** with **Winston**. Please refer the below code:

```
var winston = require('winston');
require('winston-loggly-bulk');

winston.add(winston.transports.Loggly, {
    inputToken: "token",
    subdomain: "subdomain",
    tags: ["winston"],
    json: true
    
});

 winston.log('info', 'hey there');
```

It would be a great help if you can share your code snippet and environment details(like node's version) in which you are seeing this issue. 

cc: @mostlyjason

**Comment by sloops77** [comment] 2017-06-28 20:36
Hi @Shwetajain148 
will take a look next and get back to you.

**Comment by mostlyjason** [comment] 2017-07-18 00:20
This should be fixed now so we are closing the issue. Reopen if it still happens.

**Closed as completed by mostlyjason** 2017-07-18 00:20 UTC
